[theme]
primaryColor = "#176B87"
backgroundColor = "#F7FAFC"
secondaryBackgroundColor = "#EAF2F7"
textColor = "#17324D"
font = "sans-serif"

[client]
toolbarMode = "minimal"
showErrorDetails = "full"

[server]
headless = true
runOnSave = false
